### ISSUE TITLE
Timeline gone after Euroscope restart

### ISSUE THREAD

**Issue by becas22** [EvenAR/euroscope-aman#1]
Whenever you close Euroscope and open it again, the timeline for the specific waypoint is gone. You need to add it again.

**Comment by EvenAR** [comment]
Thanks for the issue, @becas22. I will add the possibility to save the configured timelines upon exit.

**Comment by EvenAR** [comment]
Should be fixed in d37945493e267c6b481c97b24193c4fa0de2b8ba
A new .dll can be found in the release folder
