### ISSUE TITLE
initialHorizon

### ISSUE THREAD

**Issue by ghost** [EvenAR/euroscope-aman#10]
Hi,
Thanks for the plugin, I really enjoy it.
What should the initialHorizon do exactely? My AMAN-window remains at 30 minutes, regardless of what I enter for the initialHorizon. I'm using 2.0.1 and the latest Beta of ES.
Yours,
Michael

**Comment by EvenAR** [comment]
Hi, @MikeKilo01! Sorry for the late reply. I'm glad you like it!

I just realized the readme was wrong.. The name of the property is `startHorizon`.

**Comment by ghost** [comment]
No worries, I just used to scroll the timeline to my liking with the mouse wheel.
