### ISSUE TITLE
Closing timeline window

### ISSUE THREAD

**Issue by MorpheusXAUT** [EvenAR/euroscope-aman#12]
Hi,

first of all, thanks for the great ES plugin, highly appreciate your work, especially the latest 2.0.0 update!

By default, I have loaded AMAN in most of my profile, ranging from TWR to CTR positions, howeverr, I end up mostly using it when controlling an APP sector. During other session, I usually hardly use it, if at all, and thus tried closing the timeline in order to free up some screen space.

Before the update of 2.0.0, I was able to close the timeline by right-clicking the Windows taskbar entry and selecting "Close window", since the timeline itself unfortunately only has a minimize, but no close button. After the update, closing via taskbar seems to have stopped working - the window just remains unchanged.

Would it be possible to either add a control to the timeline window itself to close it (maybe even have a plugin setting to have it hidden by default, only displaying on demand, e.g. via a chat command)? If adding an extra button is not an option, could you restore the previous behaviour allowing to close via the taskbar?

**Comment by RudiZhang** [comment]
Agree with that. It will be perfect that you can add a code(like defaultshow=1/0) in .json or others. And it can display with a command ".aman" when type on euroscope

**Comment by EvenAR** [comment]
Fixed in #15
