### ISSUE TITLE
Estimated Landing Time & STAR

### ISSUE THREAD

**Issue by RudiZhang** [EvenAR/euroscope-aman#16]
thanks for the work on #15 ! Is that possible to add an Estimated Landing Time and assigned STAR in Tag layouts?

**Comment by EvenAR** [comment]
Thanks for the request! Added in [v3.1.0](https://github.com/EvenAR/euroscope-aman/releases/tag/3.1.0).

**Comment by RudiZhang** [comment]
Thanks! and a BUG was founded! 
![image](https://user-images.githubusercontent.com/40914896/122096552-fa5a0680-ce0e-11eb-8b59-db2f5d7e67ce.png)
As you can see, the time is superimposed 
![image](https://user-images.githubusercontent.com/40914896/122096632-1198f400-ce0f-11eb-9137-f61d11230d0a.png)

**Comment by EvenAR** [comment]
😬 fixed in v3.1.1, @XCSWxcsw
