### ISSUE TITLE
Tags do not show om aman ES 3.2.a(R28)

### ISSUE THREAD

**Issue by morettio** [EvenAR/euroscope-aman#17]
![Screenshot_1](https://user-images.githubusercontent.com/59777657/129186045-b762a5d6-c704-45a6-ba34-2793d1bf600d.jpg)

{
    "openAutomatically": false,
    "timelines": {
        "19R/19L": {
            "targetFixes": [ "GSW40", "GME40" ],
            "viaFixes": [ "ADOPI", "LUNIP", "ESEBA", "INREX", "RIPAM", "BELGU" ],
            "tagLayout": ""simpleLayout",
            "destinationAirports": [ "ENGM" ]
        },
        "01L/01R": {
            "targetFixes": [ "OBW40", "ONE40" ],
            "viaFixes": [ "ADOPI", "LUNIP", "ESEBA", "INREX", "RIPAM", "BELGU" ],
            "tagLayout": "myLayout",
            "destinationAirports": [ "ENGM" ]
        }
    },
    "tagLayouts": {
        "myLayout": [
            { "source": "assignedRunway", "width": 4 },
            { "source": "callsign", "width": 8 },
            { "source": "static", "defaultValue": "¤", "width": 2, "isViaFixIndicator": true },
            { "source": "aircraftType", "width": 5 },
            { "source": "aircraftWtc", "width": 2 },
            { "source": "timeBehindPreceeding", "width": 5, "rightAligned": true },
            { "source": "remainingDistance", "width": 4, "rightAligned": true },
            { "source": "static", "width": 1 },
            { "source": "directRouting", "width": 5, "rightAligned": true, "defaultValue": "-----" },
            { "source": "static", "width": 1 },
            { "source": "scratchPad", "width": 4 }
        ],
        "simpleLayout": [
            { "source": "assignedRunway", "width": 4, "isViaFixIndicator": true },
            { "source": "callsign", "width": 8 }
        ]
    }
}

**Comment by EvenAR** [comment]
I think the problem is the extra quotation mark on this line: `"tagLayout": ""simpleLayout"`. If the ID doesn't fully match it will default to an empty layout iirc.
