### ISSUE TITLE
How to resize AMAN Window?

### ISSUE THREAD

**Issue by earthjasonlin** [EvenAR/euroscope-aman#18]
The defaut AMAN window seems to be too long for my diaplay

**Comment by EvenAR** [comment]
> The defaut AMAN window seems to be too long for my diaplay

Hi, @earthjasonlin. You can resize the window by clicking and dragging the rightmost icon on the top-bar.

**Comment by earthjasonlin** [comment]
Thanks
On 9/19/2021 15:52，Even ***@***.***> wrote：

The defaut AMAN window seems to be too long for my diaplay

Hi, @earthjasonlin. You can resize the window by clicking and dragging the rightmost icon on the top-bar.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
