### ISSUE TITLE
Multiple on one timeline

### ISSUE THREAD

**Issue by ThaweK** [EvenAR/euroscope-aman#3]
Hi,

Is it possible to program it in a way that multiple (i.e. TMA entries) are on one timeline? It's exactly how it looks like in real life on one of our airports: https://ibb.co/QcMkVWX
You see it's color-coded on entries to TMA. Would love to see it, however I can't really get into your code, as C++ is not my main lang...

**Comment by EvenAR** [comment]
Hi! Sorry for the late reply. I just recently saw this issue. It sounds like a nice feature. I'll see what I can do!

**Comment by ThaweK** [comment]
Thabk you for your reply, no matter what time is it.

Another thing is, that I noticed, that assumed aircrafts has a little dot
next to timeline - is it possible to make it somehow more visible? And a
traffic that is ASEL in a border, or something? Would extremely help once
trying to manipulate the queue. Thanks in advance!

Matt.

sob., 31 paź 2020, 15:16 użytkownik Even Rognlien <notifications@github.com>
napisał:

**Comment by EvenAR** [comment]
I like the idea of highlighting the ASEL aircraft. I also changed the label color to match the dot color. This should make it easier to distinguish assumed aircraft from non-assumed. What do you think?

![image](https://user-images.githubusercontent.com/5177099/97788990-5c863400-1bbd-11eb-9ccf-7149a037367b.png)

You can find this version in the [highlight-asel](https://github.com/EvenAR/euroscope-aman/tree/highlight-asel) branch. I haven't found a good way to detect when ASEL changes, so unfortunately there is a delay of up to 1 sec before it's visible.

**Comment by ThaweK** [comment]
I would say – extremely better! This is already gonna be super useful.

If you had a spare time to try add what I mentioned earlier, that would be simply best tool I really need. If not colour coded as on the image above (but it would be great to have it this way), at least some sort of possible separation of the traffic, to just know from which side it’s coming, would be great, cuz now we only know the flow, but we don’t really know who is coming from (and as you probably know, controlling techniques are slightly different if you have a flow coming from 1 direction or when it’s coming from all possible ones 😃). I know, that I could add all of the TMA entry points as separate timelines, but I don't like it – so I set an airport that I am working on (so I’ve got all the arrivals), I just need some divergence who is coming from where).

Also, I found a quick bug: trying .aman add <point1> <point2> <time> crashes the EuroScope. (p1 p2 OR p1 <timeline minutes size> works perfectly, what it’s just not working is when you try add two codes AND time constraint). It’s so great to hear from You not seeing you here for a long time 😊

At FIR EPWW I introduced the product to the controller pack and it’s becoming more and more famous 😃

**Comment by EvenAR** [comment]
Great! I'm glad you find it useful! 😄

Ok, so regarding the picture you sent; that timeline indicates the sector entry time, and not the ETA for a final fix (like the plugin does now)?

Hmm, I can't seem to reproduce that crash 🤔 I tried `.aman add a/b 10`. The time parameter is no longer used though, since the time can now be adjusted dynamically by scrolling.

**Comment by ThaweK** [comment]
> Great! I'm glad you find it useful! 😄
> 
> Ok, so regarding the picture you sent; that timeline indicates the sector entry time, and not the ETA for a final fix (like the plugin does now)?

I asked for confirmation one of our IRL ATC for clarification:
- for ACC controllers it shows Sector Exit time (actually, based on EAT - Estimated Approach Time, so including eventual holding, but it might be too much to hassle) 
- for APP controllers it indeed shows till runway threshold (so you can set ICAO airport code for that). 

So:
1. Color coded "lines" or "callsign" depends on the predefined "via" point (TMA entry) - but calculation is still based on runway threshold (for APP behavior), 
2. If it was possible to set more than 2 points at one timeline, would simulate ACC behavior 

maybe its possible add command like .aman addvia <Points> and whenever trajectory goes through this point, it automatically set a color for, idk, callsign or something? 
I hope I clarified it now. 

> Hmm, I can't seem to reproduce that crash 🤔 I tried `.aman add a/b 10`. The time parameter is no longer used though, since the time can now be adjusted dynamically by scrolling.
Hmm, I crashed it two times before, but can't to reproduce it again, as well... 🤔

**Comment by ThaweK** [comment]
By the way, before you try implementing, I'd like to specify the behavior of the color: if you give the DCT that bypass "via" point, coloring remains.

**Comment by EvenAR** [comment]
I have done some changes to support color coded callsigns based on "via" points: [direct link](https://github.com/EvenAR/euroscope-aman/tree/highlight-asel/Release). Feel free to try it out. It's not super user friendly yet though.

How to use: `.aman add <final fix(es)> <comma separated list of via points>`
For example: `.aman add bavad/titla belgu,inrex,ripam,eseba,lunip,adopi`

![image](https://user-images.githubusercontent.com/5177099/98447344-7d520a80-2124-11eb-926c-0569d346d26b.png)

**Comment by ThaweK** [comment]
Absolutely o u t s t a n d i n g.

Love it. Thanks! 👍

**Comment by EvenAR** [comment]
Glad to hear!
