### ISSUE TITLE
Time to next aircraft calculated incorrectly.

### ISSUE THREAD

**Issue by martja** [EvenAR/euroscope-aman#4]
If my interpretation of the variable `timeToNextAircraft` is correct, it should represent how much time will pass from the current aircraft has passed the fix to the succeeding passes the fix. The current calculation of `curr->eta - next->eta` will calculate the time from the preceeding aircraft to the current aircraft.

**Comment by EvenAR** [comment]
Well, the intension is actually to show the time to the preceeding aircraft, but by the naming it should indeed be the opposite 😄 Personally I don't have any preference, so I have no problems merging your PR if you find this version more intuitve.

**Comment by martja** [comment]
I honestly don't have any preference either. Simply renaming the variable something like `timeToPrecedingAircraft` to avoid the mix-up also works.

**Comment by EvenAR** [comment]
Ok, then I think it should stay the way it works now. I will rename the variable though. Thanks for pointing it out!
